ENTRY(_Reset)

SECTIONS
{
	/* Starts at LOADER_ADDR. */
	. = 0x10000;	/* Should be 0x8000 for chip, 0x10000 for Qemu. */
	__start = .;
	__text_start = .;
	.text :
	{
		KEEP(*(.text.boot))
		*(.text*)
	}
	. = ALIGN(4096); /* align to page size */
	__text_end = .;
	
	__rodata_start = .;
	.rodata :
	{
		*(.rodata)
	}
	. = ALIGN(4096); /* align to page size */
	__rodata_end = .;

	__data_start = .;
	.data :
	{
		*(.data)
	}
	. = ALIGN(4096); /* align to page size */
	__data_end = .;

	__bss_start = .;
	.bss :
	{
		bss = .;
		*(.bss)
	}
	. = ALIGN(4096); /* align to page size */
	__bss_end = .;

	__stack_top = .;
	__end = .;
}
